databases:
  - name: busTickets
    databaseName: busTickets
    user: busTickets

services:
  - type: web
    name: busTickets
    env: python
    autoDeploy: false
    buildCommand: "./build.sh"
    startCommand: "gunicorn busTickets.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: busTickets
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4