databases:
  - name: busTickets
    databaseName: innova-DB
    user: busTickets

services:
  - type: web
    name: Api-innova
    branch: f/swagger

    region: Oregon
    rootDir: backend/busTickets
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn busTickets.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: innova-DB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4