
-- Schema of role
create table public."ticketsApp_role"
(
    id_role integer generated by default as identity
        primary key,
    name    varchar(50) not null
);

-- Schema of Road

create table public."ticketsApp_road"
(
    id           integer generated by default as identity
        primary key,
    destiny      varchar(25)      not null,
    ticket_value double precision not null,
    code         varchar(3)       not null
);

alter table public."ticketsApp_road"
    owner to postgres;



-- Schema of User

create table public."ticketsApp_user"
(
    id             integer generated by default as identity
        primary key,
    identification varchar(50) not null
        unique,
    name           varchar(50) not null,
    last_name      varchar(50) not null,
    role_id        integer     not null
        constraint "ticketsApp_user_role_id_7d36bebe_fk_ticketsApp_role_id_role"
            references public."ticketsApp_role"
            deferrable initially deferred
);

alter table public."ticketsApp_user"
    owner to postgres;

create index "ticketsApp_user_identification_356dbe67_like"
    on public."ticketsApp_user" (identification varchar_pattern_ops);

create index "ticketsApp_user_role_id_7d36bebe"
    on public."ticketsApp_user" (role_id);

-- Schema of Client

create table public."ticketsApp_client"
(
    id      integer generated by default as identity
        primary key,
    type    varchar(50) not null,
    user_id integer     not null
        constraint "ticketsApp_client_user_id_1fb75c62_fk_ticketsApp_user_id"
            references public."ticketsApp_user"
            deferrable initially deferred
);

alter table public."ticketsApp_client"
    owner to postgres;

create index "ticketsApp_client_user_id_1fb75c62"
    on public."ticketsApp_client" (user_id);

-- Schema of Box Office

create table public."ticketsApp_boxoffice"
(
    id           bigint generated by default as identity
        primary key,
    last_login   timestamp with time zone,
    address      varchar(50)              not null,
    email        varchar(50)              not null
        unique,
    username     varchar(30)              not null
        unique,
    password     varchar(256)             not null,
    date_joined  timestamp with time zone not null,
    is_admin     boolean                  not null,
    is_active    boolean                  not null,
    is_staff     boolean                  not null,
    is_superuser boolean                  not null,
    user_id      integer
        constraint "ticketsApp_boxoffice_user_id_735be973_fk_ticketsApp_user_id"
            references public."ticketsApp_user"
            deferrable initially deferred
);

alter table public."ticketsApp_boxoffice"
    owner to postgres;

create index "ticketsApp_boxoffice_email_815509b8_like"
    on public."ticketsApp_boxoffice" (email varchar_pattern_ops);

create index "ticketsApp_boxoffice_username_101fb6f8_like"
    on public."ticketsApp_boxoffice" (username varchar_pattern_ops);

create index "ticketsApp_boxoffice_user_id_735be973"
    on public."ticketsApp_boxoffice" (user_id);


--Schema of vehicle

create table public."ticketsApp_vehicle"
(
    plate           varchar(6)  not null
        primary key,
    internal_number varchar(6)  not null,
    capacity        integer     not null,
    business_id     varchar(25) not null
        constraint "ticketsApp_vehicle_business_id_73a39a13_fk_ticketsAp"
            references public."ticketsApp_business"
            deferrable initially deferred,
    user_id         integer     not null
        constraint "ticketsApp_vehicle_user_id_f4dcf9a0_fk_ticketsApp_user_id"
            references public."ticketsApp_user"
            deferrable initially deferred
);

alter table public."ticketsApp_vehicle"
    owner to postgres;

create index "ticketsApp_vehicle_plate_fc4ed1dc_like"
    on public."ticketsApp_vehicle" (plate varchar_pattern_ops);

create index "ticketsApp_vehicle_business_id_73a39a13"
    on public."ticketsApp_vehicle" (business_id);

create index "ticketsApp_vehicle_business_id_73a39a13_like"
    on public."ticketsApp_vehicle" (business_id varchar_pattern_ops);

create index "ticketsApp_vehicle_user_id_f4dcf9a0"
    on public."ticketsApp_vehicle" (user_id);


alter table public."ticketsApp_role"
    owner to postgres;



-- Schema of business
create table public."ticketsApp_business"
(
    nit             varchar(25)      not null
        primary key,
    name            varchar(50)      not null,
    withholding_tax double precision not null,
    business_code   varchar(10)      not null
        unique
);

alter table public."ticketsApp_business"
    owner to postgres;

create index "ticketsApp_business_nit_76183825_like"
    on public."ticketsApp_business" (nit varchar_pattern_ops);

create index "ticketsApp_business_business_code_819dad09_like"
    on public."ticketsApp_business" (business_code varchar_pattern_ops);

--Schema of tickets

create table public."ticketsApp_ticket"
(
    id             bigint generated by default as identity
        primary key,
    generate_date  timestamp with time zone not null,
    departure_time timestamp with time zone not null,
    value          double precision         not null,
    quantity       integer                  not null,
    state          boolean                  not null,
    total_value    double precision         not null,
    box_office_id  bigint                   not null
        constraint "ticketsApp_ticket_box_office_id_8868753c_fk_ticketsAp"
            references public."ticketsApp_boxoffice"
            deferrable initially deferred,
    client_id      integer                  not null
        constraint "ticketsApp_ticket_client_id_d9571764_fk_ticketsApp_client_id"
            references public."ticketsApp_client"
            deferrable initially deferred,
    road_id        integer                  not null
        constraint "ticketsApp_ticket_road_id_86596352_fk_ticketsApp_road_id"
            references public."ticketsApp_road"
            deferrable initially deferred,
    vehicle_id     varchar(6)               not null
        constraint "ticketsApp_ticket_vehicle_id_efe5102f_fk_ticketsAp"
            references public."ticketsApp_vehicle"
            deferrable initially deferred
);

alter table public."ticketsApp_ticket"
    owner to postgres;

create index "ticketsApp_ticket_box_office_id_8868753c"
    on public."ticketsApp_ticket" (box_office_id);

create index "ticketsApp_ticket_client_id_d9571764"
    on public."ticketsApp_ticket" (client_id);

create index "ticketsApp_ticket_road_id_86596352"
    on public."ticketsApp_ticket" (road_id);

create index "ticketsApp_ticket_vehicle_id_efe5102f"
    on public."ticketsApp_ticket" (vehicle_id);

create index "ticketsApp_ticket_vehicle_id_efe5102f_like"
    on public."ticketsApp_ticket" (vehicle_id varchar_pattern_ops);

-- Schema PayRoll

create table public."ticketsApp_payroll"
(
    id             integer generated by default as identity
        primary key,
    date           date             not null,
    discount       varchar(20)      not null,
    retention      double precision not null,
    date_start     date             not null,
    date_end       date             not null,
    "boxOffice_id" bigint           not null
        constraint "ticketsApp_payroll_boxOffice_id_bbda7bc5_fk_ticketsAp"
            references public."ticketsApp_boxoffice"
            deferrable initially deferred,
    vehicle_id     varchar(6)       not null
        constraint "ticketsApp_payroll_vehicle_id_0addb8c7_fk_ticketsAp"
            references public."ticketsApp_vehicle"
            deferrable initially deferred
);

alter table public."ticketsApp_payroll"
    owner to postgres;

create index "ticketsApp_payroll_boxOffice_id_bbda7bc5"
    on public."ticketsApp_payroll" ("boxOffice_id");

create index "ticketsApp_payroll_vehicle_id_0addb8c7"
    on public."ticketsApp_payroll" (vehicle_id);

create index "ticketsApp_payroll_vehicle_id_0addb8c7_like"
    on public."ticketsApp_payroll" (vehicle_id varchar_pattern_ops);